version: "3.7"

services:
  web:
    container_name: "laravel9_web"
    build:
      context: .
      target: "local"
    ports:
      - "14080:443"
    volumes:
      - .:/var/www/
      - ./.docker/nginx/conf.d/default_local.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/cert/:/etc/nginx/cert/
      - ./.docker/php/8.1/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/zzz-www.conf
      - ./.docker/php/8.1/php.ini:/usr/local/etc/php/conf.d/my-app.ini
    links:
      - db
      - redis
      - mailcatcher
  mailcatcher:
    image: yappabe/mailcatcher
    container_name: "laravel9_mailcatcher"
    ports:
      - "14025:1025"
      - "14088:1080"
  db:
    image: mysql:5.7.12
    container_name: "laravel9_mysql"
    ports:
      - "15326:3306"
    volumes:
      - ./.docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./.docker/mysql/charset.cnf:/etc/mysql/conf.d/charset.cnf
      - ./.db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=laravel9
  redis:
    image: redis
    container_name: "laravel9_redis"
    ports:
      - "18379:6379"
volumes:
  redis-data:
    driver: local
